config/routes.rb
Rails.application.routes.draw do
  
  root                  'events#index'

  get     'signup'              =>  'users#new',    as:   'signup'
  post    'users'               =>  'users#create'
  #get     'users/:id'           =>  'users#show',   as:   'user'

  get     'login'               =>  'sessions#new',     as:   'login'
  post    'login'               =>  'sessions#create'
  delete  'logout'              =>  'sessions#destroy', as:   'logout'
  
  get     'events/:id'          =>  'events#show',  as: 'event'
  get     'events'              =>  'events#index'

  get     'register/:id'        =>  'event_registrations#register_user',        as: 'register_user'
  get     'deletereg/:id'       =>  'event_registrations#delete_registration', as: 'delete_registration'

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :event_registrations
  has_many :users, through: :event_registrations
end

app/models/event_registration.rb
class EventRegistration < ActiveRecord::Base
  belongs_to :user
  belongs_to :event

  validates :user_id,   :uniqueness => {:scope => :event_id}
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token
  has_many :event_registrations
  has_many :events, through: :event_registrations

  before_save { self.email = email.downcase }
  validates :name,    presence: true,
                      length: { maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email,   presence: true,
                      length: { maximum: 250 },
                      format: { with: VALID_EMAIL_REGEX },
                      uniqueness: { case_sensitive: false }

  VALID_GENDER_REGEX= /[M,F]/
  validates :gender,  presence: true,
                      length: { maximum: 1 },
                      format: { with: VALID_GENDER_REGEX }

  has_secure_password
  validates :password, length: { minimum: 8 }

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  include EventRegistrationsHelper

  private
    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
end

app/controllers/event_registrations_controller.rb
class EventRegistrationsController < ApplicationController

  def register_user
    if logged_in?
      add_registration(current_user.id,params[:event_id])
      redirect_to event_path(:id => params[:event_id])
    else
      session[:return_to] ||= event_path(:event_id => params[:event_id])
      redirect_to login_path
    end
  end

  def delete_registration
    if logged_in?
      delete_user_registration(current_user.id,params[:event_id])
      redirect_to event_path(:id => params[:event_id])
    else
      session[:return_to] ||= event_path(:event_id => params[:event_id])
      redirect_to login_path
    end
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.all.order(created_at: :desc)
  end

  def show
    @event = Event.find(params[:id])
    @user = current_user
    @registered_users = User.joins(:event_registrations).where('event_registrations.event_id = ?', params[:id])
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if logged_in?
      redirect_to root_url
    end
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      if session[:return_to]
        redirect_to session.delete(:return_to)
      else
        redirect_to root_url
      end
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to EventZilla!"
      redirect_to root_url
    else
      render 'new'
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :gender, :password,
                                   :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = "EventZilla"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/event_registrations_helper.rb
module EventRegistrationsHelper
  def is_registered(event, user)
    if logged_in?
      user_registration = User.joins(:event_registrations).where('event_registrations.event_id = ? AND event_registrations.user_id = ?', event.id, current_user.id)
      if user_registration.blank?
        return false
      else 
        return true
      end
    end
  end

  def add_registration(u_id, e_id)
    user_registration = User.joins(:event_registrations).where('event_registrations.event_id = ? AND event_registrations.user_id = ?', e_id, u_id)
    if user_registration.blank?
      event_registration = EventRegistration.new(:user_id => u_id, :event_id => e_id)
      event_registration.save
      flash[:success] = "Event Registration Successful."
    end
  end

  def delete_user_registration(u_id, e_id)
    user_registration = EventRegistration.find_by(user_id: u_id, event_id: e_id)
    if not user_registration.blank?
      user_registration.delete
      flash[:success] = "Event Registration Canceled."
    end
  end

end

app/helpers/events_helper.rb
module EventsHelper
  def is_past_event(event)
    return true if event.date_time < DateTime.now
    return false
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

  def is_female?(user)
    if logged_in?
      return true if user.gender == 'F'
    end
    return false
  end
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :date_time %><br>
    <%= f.datetime_select :date_time %>
  </div>
  <div class="field">
    <%= f.label :venue %><br>
    <%= f.text_field :venue %>
  </div>
  <div class="field">
    <%= f.label :ticket %><br>
    <%= f.number_field :ticket %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/index.html.erb
<div class="jumbotron">
    <% provide(:title, "Welcome") %>
    <p id="notice"><%= notice %></p>
    <h2>Events</h2>
    <br/>
    <ul class="list-group">
    <% @events.each do |event| %>
        <li class="list-group-item">
            <span class="badge">Created: <%= event.created_at %></span>
            <%= link_to "#{event.name}", event %>
        </li>
    <% end %>
    </ul>
    <br/>
</div>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<div class="col-md-9">
    <div class="panel panel-info">
      <div class="panel-heading">
        <h3 class="panel-title"><%= @event.name %> <small>(<%= @event.venue %>)</small>
            <span class="pull-right">
                <% if logged_in? %>
                    <% if !is_past_event(@event) %>
                      <% if is_registered(@event, @user) %>
                        <%= link_to 'Unattend', delete_registration_path(:event_id => @event.id) %>
                      <% else %>
                        <%= link_to 'Attend', register_user_path(:event_id => @event.id) %>
                      <% end %>
                    <% else %>
                      Registrations Closed
                    <% end %>
                <% end %>
            </span>
        </h3>
      </div>
      <div class="panel-body">
        <%= @event.description %>
      </div>
      <div class="panel-footer">Date & Time: <%= @event.date_time %>
        <span class="pull-right">
          Ticket: <% if is_female?(@user) %>
                    <strike>&#8377;<%= @event.ticket %></strike>  &#8377;<%= @event.ticket * 0.95 %> (5% Girls Discount)
                  <% else %>
                    &#8377;<%= @event.ticket %>
                  <% end %>
        </span>
      </div>
    </div>
</div>
<div class="col-md-3">
    <div class="panel panel-info">
      <div class="panel-heading">
        <h3 class="panel-title">All Attendees</h3>
      </div>
      <div class="panel-body">
        <% if @registered_users.empty? %>
          <p>No registrations so far.</p>
        <% else %>
          <table class="table">
            <thead>
              <tr>
                <td>Name</td>
                <td>Gender</td>
              </tr>
            </thead>
            <tbody>
            <% @registered_users.each do |usr| %>
            <tr>
                <td><%= usr.name %></td>
                <td><%= usr.gender %></td>
            </tr>
            <% end %>
            </tbody>
          </table>
        <% end %>
      </div>
    </div>
</div>

<div class="col-md-12"><center><%= link_to '<< Back to Events', events_path %></center></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">EventZilla</a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <% if logged_in? %>
                <li><%= link_to "Log out", logout_path, method: "delete" %></li>
            <% else %>
                <li><%= link_to "Log in", login_path %></li>
                <li><%= link_to "Sign up", signup_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>

  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div clas="error_div" id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<%= form_for @user, :html => {:class => "form-signup"} do |f| %>
    <h3 class="form-heading">Signup</h3>
    <%= render 'shared/error_messages' %>
    <%= f.label :name, :class => 'sr-only'  %>
    <%= f.text_field :name, :class => 'form-control form-top', :placeholder => "Name" %>

    <%= f.label :email, :class => 'sr-only'  %>
    <%= f.email_field :email, :class => 'form-control form-middle', :placeholder => "Email" %>

    <%= f.label :gender, :class => 'sr-only'  %>
    <%= f.text_field :gender, :class => 'form-control form-middle', :placeholder => "Gender (M or F)" %>

    <%= f.label :password, :class => 'sr-only'  %>
    <%= f.password_field :password, :class => 'form-control form-middle', :placeholder => "Password (Minimum 8 Chars)" %>

    <%= f.label :password_confirmation, "Confirmation", :class => 'sr-only'  %>
    <%= f.password_field :password_confirmation, :class => 'form-control form-bottom', :placeholder => "Confirm Password" %>

    <%= f.submit "Create my account", class: "btn btn-primary form-button" %>
<% end %>

app/views/users/show.html.erb
<%= provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>